apiVersion: v1
kind: Service
metadata:
  name: ragsystem-backend
spec:
  selector:
    app: ragsystem-backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
  type: ClusterIP
