apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ragsystem.frontendname" . | default "ragsystem-frontend" }}
  labels:
    app: ragsystem-frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: ragsystem-frontend
  template:
    metadata:
      labels:
        app: ragsystem-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.frontend.repository }}:{{ .Values.image.frontend.tag }}"
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.frontend.port }}
          resources:
            limits:
              cpu: {{ .Values.resources.frontend.limits.cpu }}
              memory: {{ .Values.resources.frontend.limits.memory }}
            requests:
              cpu: {{ .Values.resources.frontend.requests.cpu }}
              memory: {{ .Values.resources.frontend.requests.memory }}
